export { default as Cancelled } from './cancelled/Cancelled';
export { default as Navbar } from './Navbar/Navbar';
export { default as Finished } from './finished/Finished';
export { default as Newsec } from './newsec/Newsec';
export { default as Ongoing } from './ongoing/Ongoing';
export { default as Task } from './Task/Task';
export { default as Addingpanel } from './addingpanel/Addingpanel';
export { default as Member } from './member/Member';
export { default as Memberlist } from './memberslist/Memberslist';
